# Generated by Django 4.1.2 on 2022-10-27 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="İlan ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=256, verbose_name="İlan Başlığı"),
                ),
                ("detaylar", models.TextField(verbose_name="İlan Detayları")),
                ("pozisyon", models.CharField(max_length=256, verbose_name="Pozisyon")),
                (
                    "deneyim",
                    models.IntegerField(
                        choices=[
                            (0, "Stajyer"),
                            (1, "Başlangıç Seviye"),
                            (2, "Uzman"),
                            (3, "Üst Düzey"),
                            (4, "Yönetici"),
                            (5, "Hepsi"),
                        ],
                        default=5,
                        verbose_name="Deneyim Düzeyi",
                    ),
                ),
                (
                    "ilan_turu",
                    models.IntegerField(
                        choices=[
                            (0, "Tam Zamanlı"),
                            (1, "Yarı Zamanlı"),
                            (2, "Freelance"),
                        ],
                        default=2,
                        verbose_name="İlan Türü",
                    ),
                ),
                (
                    "calisma_sekli",
                    models.IntegerField(
                        choices=[(0, "İş Yerinde"), (1, "Uzaktan"), (2, "Hibrit")],
                        default=0,
                        verbose_name="Çalışma Şekli",
                    ),
                ),
                (
                    "aday_sayisi",
                    models.IntegerField(verbose_name="Alınacak aday sayısı"),
                ),
                ("sirket", models.CharField(max_length=256, verbose_name="Şirket Adı")),
                (
                    "ilan_tarihi",
                    models.DateTimeField(auto_now_add=True, verbose_name="İlan Tarihi"),
                ),
                (
                    "guncelleme",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "İş İlanı",
                "verbose_name_plural": "İş İlanları",
            },
        ),
    ]
