# Generated by Django 4.1.2 on 2022-10-27 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="adaylar",
            field=models.ManyToManyField(
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Başvuran Kişiler",
            ),
        ),
        migrations.AddField(
            model_name="jobs",
            name="etiketler",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="jobs",
            name="ilan_sahibi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="İlan Sahibi",
            ),
        ),
    ]
