# Generated by Django 4.1.2 on 2022-10-29 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="adaylar",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Başvuran Kişiler",
            ),
        ),
    ]
